# Generated by Django 4.1.1 on 2022-09-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="discount_price",
            field=models.FloatField(blank=True),
        ),
    ]
